spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/firstshop
    username: rudah
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      location: C:/first_shop/item
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
file:
  dir: C:/first_shop/item

itemImgLocation: C:/first_shop/item

logging:
  level:
    root: debug

