spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/firstshop
    username: rudah
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
logging:
  level:
    root: INFO

